version: 0.2

phases:
    pre_build:
        commands:
          - echo "Installing Packer"
          - curl -o packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && unzip packer.zip
          - echo "Validating Packer template"
          - ./packer validate $PACKER_SCRIPT.json
    build:
        commands:
          - echo "Starting Packer Build"
          - ./packer build -color=false $PACKER_SCRIPT.json | tee build.log
    post_build:
        commands:
          - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
          - test -s ami_id.txt || exit 1
          - echo "build completed on `date`"
artifacts:
    files:
        - build.log
    discard-paths: yes
